Update references to maistra/istio to latest maistra-1.1 commit
maistra/prometheus pull request #4
Opened 2020-01-27 11:46 UTC by dgn

2020-01-27 13:29 UTC, knrc requested changes
From an email discussion with Daniel I believe this is based on the wrong version of prometheus so we should not be merging this.

2020-01-27 17:29 UTC, dgn commented
As discussed in the call, I verified this works against Maistra 1.0 and have no reason to believe it won't work with 1.1.

For context: upstream Istio uses Prometheus v2.12.0, we're using an OpenShift fork of prometheus. OpenShift have no release for 2.12: the 4.2 build is based off of 2.11.2, the 4.3 one 2.14.0 - I rebased to 2.14.0 (branch `release-4.3` in openshift/prometheus), as this version has been tested against OCP 4.3. We will need to monitor whether this introduces problems, but it all looks good for now.

2020-01-27 17:35 UTC, knrc approved these changes

2020-01-28 15:34 UTC, brian-avery approved these changes

2020-01-28 15:56 UTC, merged